### ISSUE TITLE
Village : 

### ISSUE THREAD

**Issue by ONEmanLAW** [ONEmanLAW/Tanu-s-Quest#12]
### Choses a faire pour le village :
**Crée 3 village :**

- [ ] Village Détruit 
- [ ] Village Motié Détruit
- [ ] Village Reconstruit

**TODO dans Village Détruit :**

- [ ] Ajouté Yeti au bonne emplacement.
- [ ] Ajouté du bon dialogue pour le Yeti.
- [ ] Crée un système de dialogue et de retour en arrière quand il se rapproche d'une autre carte que celle ou il doit aller.

_**Facultatif :**_  

- [ ] Ajouté des dialogue a des endroit pour apporter du dialogue.

**TODO dans Village Motié Détruit :**

- [ ] Ajout de Yeti au bonne emplacement.
- [ ] Ajout du bon dialogue pour le Yeti.
- [ ] Ajout de la nouvelle arme pour Tanu quand il va voire le Yeti.
- [ ] Une fois qu'il a la nouvelle arme l'écorce disparais 
- [ ] Ajout de l'alchimiste au bonne endroit.
- [ ] Ajout du bon dialogue avec l'alchimiste.
- [ ] Ajout de la function qui permet de ce mettre de la vie avec les coeur **(IMPORTANT)**
- [ ] Ajout de villageois au bonne endroit.
- [ ] Ajout de dialogue avec les villageois en appuyant sur 'e'.
- [ ] Crée un système de dialogue et de retour en arrière quand il se rapproche d'une autre carte que celle ou il doit aller.

_**Facultatif :**_  

- [ ] Ajouté des dialogue a des endroit pour apporter du dialogue.

**TODO dans village Construit:**

- [ ] Ajout de tout les villageois.
- [ ] Ajout du bon dialogue pour le Yeti
- [ ] Ajout du bon dialogue pour l'alchimiste.
- [ ] Quand il retourne voir l'alchimiste les coeur retourne au max et il récupère toute les potions.  
- [ ] Crée un système de dialogue et de retour en arrière quand il se rapproche d'une autre carte que celle ou il doit aller.

_**Facultatif :**_  

- [ ] Ajouté des dialogue a des endroit pour apporter du dialogue.

**EN PLUS :**

- [ ] Tout les assets designer fournit.
